sites_index:
    path:     /admin/
    defaults: { _controller: "AppBundle:Sites:index" }
    methods:  GET

sites_show:
    path:     /admin/{id}/show
    defaults: { _controller: "AppBundle:Sites:show" }
    methods:  GET

sites_new:
    path:     /admin/new
    defaults: { _controller: "AppBundle:Sites:new" }
    methods:  [GET, POST]

sites_edit:
    path:     /admin/{id}/edit
    defaults: { _controller: "AppBundle:Sites:edit" }
    methods:  [GET, POST]

sites_delete:
    path:     /admin/{id}/delete
    defaults: { _controller: "AppBundle:Sites:delete" }
    methods:  DELETE
