app_media:
    resource: "@AppBundle/Resources/config/routing/media.yml"
    prefix:   /media

app_sites:
    resource: "@AppBundle/Resources/config/routing/sites.yml"
    prefix:   /sites

app_contact:
    path:     /contact
    defaults: { _controller:  }
