app_media:
    resource: "@AppBundle/Resources/config/routing/media.yml"
    prefix:   /admin/media

app_sites:
    resource: "@AppBundle/Resources/config/routing/sites.yml"
    prefix:   /admin/sites


